site_name: Zhikang Lai | Personal Site
site_author: Zhikang Lai
site_url: https://zhikanglai.github.io

nav:
  - About Me: index.md

theme: 
  name: mkdocs
  font:
    text: Roboto

plugins: [] 

extra_css:
  - stylesheets/extra.css

extra:
  favicon: img/favicon.png